languageCode = "en-uk"
title = "Illustration portfolio"
pluralizeListTitles = "false"
baseURL = "/"
theme = "lemon-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Work"
    url = "/#work"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    name = "Get in touch"
    url = "/get-in-touch"
    weight = 4

[params]
  email = "hello@laurasnclr.com"
  name = "Laura Sinclair"
  tagline = "Illustration & creative artwork"

  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/laura.snclr/"

  [[params.social]]
    name = "behance"
    url = "https://www.behance.net/laurasnclr"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/laurasnclr/"

[related]
    treshold = 1
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "CurrentSection.Title"
        weight = 75
    [[related.indices]]
        name = "Section.Title"
        weight = 50
    [[related.indices]]
        name = "description"
        weight = 25

[build]
  [build.sass]
    noDeprecationWarnings = true